// Package config provides configuration parsing and validation for Traffic Orchestrator.
package config

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"
)

// AgentConfFile is the legacy filename kept for internal references.
const AgentConfFile = "agent.conf"

// ToConfFile is the unified auto-start configuration file (v0.3.1+).
// When the binary is invoked without arguments it looks for this file and
// auto-detects whether to start as master or agent based on its content.
const ToConfFile = "to.conf"

// ToConfModeMaster and ToConfModeAgent are the return values of DetectToConfMode.
const (
	ToConfModeMaster = "master"
	ToConfModeAgent  = "agent"
)

// DetectToConfMode reads the first meaningful lines of path and returns
// ToConfModeMaster or ToConfModeAgent:
//
//   - "[MASTER]" section header   → master (traffic config format)
//   - "TCP …" / "UDP …" rule line → master
//   - "MASTER=<host>" key=value   → agent
//
// Returns an error if the file cannot be opened or the mode cannot be determined.
func DetectToConfMode(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// INI section header [MASTER] → traffic / master config
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			return ToConfModeMaster, nil
		}

		// Traffic rule line: starts with TCP or UDP → master config
		upper := strings.ToUpper(line)
		if strings.HasPrefix(upper, "TCP ") || strings.HasPrefix(upper, "UDP ") {
			return ToConfModeMaster, nil
		}

		// Key=value line
		if idx := strings.Index(line, "="); idx != -1 {
			key := strings.TrimSpace(strings.ToUpper(line[:idx]))
			if key == "MASTER" {
				// "MASTER=<host>" means this is an agent connection config
				return ToConfModeAgent, nil
			}
			// Other key=value lines (PORT, PSK, target defs) — keep scanning
		}
	}

	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("read error in %s: %w", path, err)
	}
	return "", fmt.Errorf("cannot determine mode from %s (no [MASTER] section, no TCP/UDP rules, no MASTER= key found)", path)
}

// LoadAgentConf reads an AgentConfig from a file written by SaveAgentConf.
// Supported keys (case-insensitive): MASTER, PORT, PSK, ID.
// Inline comments (# …) are stripped. Returns an error if the file does not
// exist, cannot be read, or is missing required fields.
func LoadAgentConf(path string) (*AgentConfig, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err // caller distinguishes os.IsNotExist
	}
	defer f.Close()

	cfg := &AgentConfig{}
	scanner := bufio.NewScanner(f)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		idx := strings.Index(line, "=")
		if idx < 0 {
			continue
		}

		key := strings.TrimSpace(strings.ToUpper(line[:idx]))
		value := strings.TrimSpace(line[idx+1:])

		// Strip trailing inline comment
		if ci := strings.Index(value, " #"); ci >= 0 {
			value = strings.TrimSpace(value[:ci])
		}

		switch key {
		case "MASTER":
			cfg.MasterHost = value
		case "PORT":
			port, err := strconv.Atoi(value)
			if err != nil || port <= 0 || port > 65535 {
				return nil, fmt.Errorf("%s: invalid PORT value %q", path, value)
			}
			cfg.Port = port
		case "PSK":
			cfg.PSK = value
		case "ID":
			cfg.AgentID = value
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("%s: read error: %w", path, err)
	}

	// Validate required fields
	if cfg.MasterHost == "" {
		return nil, fmt.Errorf("%s: MASTER is required", path)
	}
	if cfg.Port == 0 {
		return nil, fmt.Errorf("%s: PORT is required", path)
	}
	if cfg.PSK == "" {
		return nil, fmt.Errorf("%s: PSK is required", path)
	}
	if cfg.AgentID == "" {
		cfg.AgentID = "agent-unknown"
	}

	return cfg, nil
}

// SaveAgentConf persists an AgentConfig to path in KEY=VALUE format.
// The file is written atomically (temp file + rename) so a crash during
// the write never leaves a corrupt config behind.
func SaveAgentConf(path string, cfg *AgentConfig) error {
	tmp := path + ".tmp"

	f, err := os.Create(tmp)
	if err != nil {
		return fmt.Errorf("cannot create %s: %w", tmp, err)
	}

	w := bufio.NewWriter(f)
	fmt.Fprintf(w, "# %s — generated by Traffic Orchestrator on %s\n", path, time.Now().Format("2006-01-02 15:04:05"))
	fmt.Fprintf(w, "# Delete this file to reset to interactive startup.\n\n")
	fmt.Fprintf(w, "MASTER=%s\n", cfg.MasterHost)
	fmt.Fprintf(w, "PORT=%d\n", cfg.Port)
	fmt.Fprintf(w, "PSK=%s\n", cfg.PSK)
	if cfg.AgentID != "" && cfg.AgentID != "agent-unknown" {
		fmt.Fprintf(w, "ID=%s\n", cfg.AgentID)
	}

	if err := w.Flush(); err != nil {
		f.Close()
		os.Remove(tmp)
		return fmt.Errorf("cannot write %s: %w", tmp, err)
	}
	f.Close()

	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return fmt.Errorf("cannot save %s: %w", path, err)
	}

	return nil
}
